#!/usr/bin/env bash

export CONTECO_LABEL="package.metrics_node - ModEco"
export CONTECO_DESCRIPTION="The ModEco metrics node module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="metrics_node"
export CONTECO_TAG="7.9.2"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
