#!/usr/bin/env bash


prefix="package_metrics_node_$2"

if [[ "package_metrics_node_metrics_node_metrics_node_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_metrics_node_metrics_node_metrics_node_volume
	fi
	
