#!/usr/bin/env bash


prefix="package_$2"


executionplane --silent docker container prune --force

if [[ "package_metrics_node_metrics_node_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume rm --force package_metrics_node_metrics_node_volume
	fi
	
